#!/bin/sh

#############
# Initial setup for the thin-client server
#
# https://github.com/fabianorosas/thinarch
############

root="${1:-/srv/arch}"

## locale:
sed -i 's/^#\(en_US\.UTF-8 UTF-8\)/\1/' "$root/etc/locale.gen"
sed -i 's/^#\(pt_BR\.UTF-8 UTF-8\)/\1/' "$root/etc/locale.gen"
arch-chroot "$root" locale-gen
echo LANG=en_US.UTF-8 > "$root/etc/locale.conf"

## timezone:
arch-chroot "$root" ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
hwclock --hctosys --localtime

## video drivers
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S xf86-video-ati
#pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S xf86-video-intel

## input drivers
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S xf86-input-synaptics

## desktop environment
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S gtk2-xfce-engine gtk3-xfce-engine thunar thunar-volman xfce4-appfinder xfce4-panel xfce4-session xfce4-settings xfce4-terminal xfconf xfdesktop xfwm4

## fonts
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S ttf-dejavu

## devel tools
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S gcc gedit git

## gvfs (mount drives)
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S gvfs

## pdf stuff
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S poppler evince

## latex
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S texlive-core texlive-latexextra texlive-publishers

## users
sudo thinarch -a users minicurso

## other files
sudo ./thinarch -f handout_latex_2014-2.pdf
sudo thinarch -r "git clone https://github.com/UTFPR-PG/latex.git /home/\$login/classeUTFPR"
sudo thinarch -r "chown -R \$login:minicurso /home/\$login/"
